language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
env:
  - DJANGO=1.4.13
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.7
  - DJANGO=1.8
matrix:
  exclude:
   - python: 3.3
     env: DJANGO=1.4.13
   - python: 3.4
     env: DJANGO=1.4.13
   - python: 2.6
     env: DJANGO=1.7.7
   - python: 2.6
     env: DJANGO=1.8
install: pip install -q Django==$DJANGO
script: python setup.py test
