language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
env:
  - DJANGO=1.4.13
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.11
  - DJANGO=1.8.7
  - DJANGO=1.9
matrix:
  exclude:
   - python: 3.3
     env: DJANGO=1.4.13
   - python: 3.3
     env: DJANGO=1.9
   - python: 3.4
     env: DJANGO=1.4.13
   - python: 3.5
     env: DJANGO=1.4.13
   - python: 3.5
     env: DJANGO=1.5.12
   - python: 3.5
     env: DJANGO=1.6.11
   - python: 3.5
     env: DJANGO=1.7.11
   - python: 2.6
     env: DJANGO=1.7.11
   - python: 2.6
     env: DJANGO=1.8.7
   - python: 2.6
     env: DJANGO=1.9
install: pip install -q Django==$DJANGO
script: python setup.py test
