language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
env:
  - DJANGO=1.4.13
  - DJANGO=1.5.8
  - DJANGO=1.6.5
  - DJANGO=1.7.1
matrix:
  exclude:
   - python: 3.3
     env: DJANGO=1.4.13
   - python: 3.4
     env: DJANGO=1.4.13
   - python: 2.6
     env: DJANGO=1.7.1
install: pip install -q Django==$DJANGO
script: python setup.py test
